### ISSUE TITLE
Upload built wheels to PyPI

### ISSUE THREAD

**Issue by sassy-asjp** [GorgiAstro/orekit-pip#2]
Is there something blocking wheels built from this from being uploaded to PyPI so it can be installed using pip normally instead of via git (and having to build every time)?

**Comment by GorgiAstro** [comment]
Hi, it's not possible to upload the built wheels to PyPi, you will get the following error "wheel is not manylinux_2_34 compliant because it links the following forbidden libraries: libjvm.so".

This repo was more a sandbox, I actually gave up (although it actually works, it just takes ages to build the wheel locally every time), because I am working with Petrus on the new jpype-based Orekit Python wrapper which is better IMO: https://gitlab.orekit.org/orekit/orekit_jpype
This new wrapper will be released very soon on PyPi. It comes with a few small limitations and differences from the old JCC wrapper, this is documented in the README.md of the repo https://gitlab.orekit.org/orekit/orekit_jpype

I will set this repo to archive mode to indicate that I'm not working on it actively anymore.

**Comment by GorgiAstro** [comment]
Hi @sassy-asjp the new Orekit jpype Python wrapper is now available on PyPi :) https://pypi.org/project/orekit-jpype/
